#!/usr/bin/env python3

from src.core import init_core_module
from src.cli import main_function
import configparser
import os
import sys
from pathlib import Path

script_dir = Path(sys.executable).parent
config_file_path = os.path.join(script_dir, 'expman.conf')
config = configparser.ConfigParser()
config.read(config_file_path)

if __name__ == "__main__":
    init_core_module(config['database']['path'], config['database']['name'])
    main_function()