#!/usr/bin/env python3

from src.core import init_core_module
from src.cli import main_function
import configparser
import os
import sys
from pathlib import Path


if getattr(sys, 'frozen', False):
    # The program is running as a compiled executable
    script_dir = Path(sys.executable).parent
    config_file_path = os.path.join(script_dir, 'expman.conf')
else:
    # The program is running as a standard Python script
    print("Running as developer")
    print(f"Script path: {Path(__file__).parent}")
    script_dir = Path(__file__).parent
    config_file_path = os.path.join(script_dir, 'expman.conf')

config = configparser.ConfigParser()
config.read(config_file_path)

if __name__ == "__main__":
    init_core_module(config['database']['path'], config['database']['name'])
    main_function()