#!/usr/bin/env python3

from src.core import init_core_module
from src.cli import main_function
import configparser

config = configparser.ConfigParser()
config.read('expman.conf')

if __name__ == "__main__":
    init_core_module(config['database']['path'], config['database']['name'])
    main_function()